import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const day = (n = 0) => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0, 10); };
const money = n => `$${Number(n || 0).toFixed(0)}`;
const date = n => new Date(`${n}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
const api = async (url, options = {}, token) => { const r = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await r.json(); if (!r.ok) throw Error(data.error || "Something went wrong."); return data; };

function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem("roadwise-session") || "null"));
  const [view, setView] = useState("fleet"), [types, setTypes] = useState([]), [vehicles, setVehicles] = useState([]), [bookings, setBookings] = useState([]), [payments, setPayments] = useState([]), [selected, setSelected] = useState(null), [notice, setNotice] = useState("");
  const [filter, setFilter] = useState("All vehicles"), [dates, setDates] = useState({ startDate: day(1), endDate: day(4) });
  const signedIn = !!session;
  const signOut = () => { localStorage.removeItem("roadwise-session"); setSession(null); setView("fleet"); };
  const loadFleet = () => api(`/api/vehicles?${new URLSearchParams({ ...(filter !== "All vehicles" ? { type: filter } : {}), ...dates })}`).then(setVehicles).catch(e => setNotice(e.message));
  const loadAccount = () => { if (!session) return; Promise.all([api("/api/bookings", {}, session.token), api("/api/payments", {}, session.token)]).then(([b,p]) => { setBookings(b); setPayments(p); }).catch(e => { setNotice(e.message); signOut(); }); };
  useEffect(() => { api("/api/types").then(setTypes).catch(e => setNotice(e.message)); }, []);
  useEffect(() => { loadFleet(); }, [filter, dates.startDate, dates.endDate]);
  useEffect(loadAccount, [session?.token]);
  const loggedIn = s => { localStorage.setItem("roadwise-session", JSON.stringify(s)); setSession(s); setView(s.user.role === "admin" ? "admin" : "fleet"); };
  const book = async e => { e.preventDefault(); if (!session) return setSelected("auth"); const f = new FormData(e.currentTarget); try { await api("/api/bookings", { method: "POST", body: JSON.stringify({ vehicleId: selected.id, startDate: f.get("startDate"), endDate: f.get("endDate"), pickupLocation: f.get("pickupLocation") }) }, session.token); setSelected(null); setNotice("Reservation confirmed — your trip is on the road."); loadAccount(); loadFleet(); } catch (e) { setNotice(e.message); } };
  if (session?.user.role === "admin") return <Admin session={session} onLogout={signOut} />;
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView("fleet")}><span className="brand-mark">R</span>roadwise</button><nav className="main-nav"><button className={view === "fleet" ? "active" : ""} onClick={() => setView("fleet")}>Explore fleet</button>{signedIn && <><button className={view === "trips" ? "active" : ""} onClick={() => setView("trips")}>My trips <span className="nav-count">{bookings.length}</span></button><button className={view === "payments" ? "active" : ""} onClick={() => setView("payments")}>Payments</button></>}</nav><div className="profile">{signedIn ? <><span className="status-dot"/><span>{session.user.fullName}</span><button className="text-button" onClick={signOut}>Log out</button><span className="avatar">{session.user.fullName.split(" ").map(x=>x[0]).join("")}</span></> : <button className="login-button" onClick={() => setSelected("auth")}>Sign in</button>}</div></header><main>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}{view === "fleet" ? <Fleet {...{types,vehicles,filter,setFilter,dates,setDates,onBook:setSelected}}/> : view === "trips" ? <Trips bookings={bookings} onExplore={() => setView("fleet")}/> : <Payments payments={payments}/>}</main>{selected === "auth" && <Auth onDone={loggedIn} onClose={() => setSelected(null)}/>} {selected && selected !== "auth" && <Booking vehicle={selected} dates={dates} onClose={() => setSelected(null)} onBook={book}/>}</div>;
}
function Fleet({types,vehicles,filter,setFilter,dates,setDates,onBook}) { return <><section className="hero"><div className="hero-copy"><p className="eyebrow">THE OPEN ROAD, ORGANIZED</p><h1>Go somewhere<br/><em>worth going.</em></h1><p className="hero-intro">Well-kept vehicles, transparent pricing, and the freedom to take the long way home.</p></div><div className="route-card"><div className="route-card-head"><span>PLAN YOUR DRIVE</span><span className="live-pill">● Live availability</span></div><div className="date-fields"><label>Pick-up date<input type="date" min={day()} value={dates.startDate} onChange={e=>setDates({...dates,startDate:e.target.value})}/></label><span className="arrow">→</span><label>Return date<input type="date" min={dates.startDate} value={dates.endDate} onChange={e=>setDates({...dates,endDate:e.target.value})}/></label></div><button className="search-button" onClick={()=>document.getElementById("fleet").scrollIntoView({behavior:"smooth"})}>Find a vehicle <span>↗</span></button></div></section><section className="section-heading" id="fleet"><div><p className="eyebrow">A FLEET WITH A POINT OF VIEW</p><h2>Choose your <em>pace.</em></h2></div><div className="fleet-meta"><strong>{vehicles.length}</strong> vehicles available<br/><span>for your selected dates</span></div></section><div className="type-filters"><button className={filter==="All vehicles"?"selected":""} onClick={()=>setFilter("All vehicles")}>All vehicles</button>{types.map(t=><button className={filter===t.name?"selected":""} onClick={()=>setFilter(t.name)} key={t.id}>{t.name}</button>)}</div><section className="vehicle-grid">{vehicles.map(v=><article className="vehicle-card" key={v.id}><div className="vehicle-image"><img src={v.imageUrl} alt={`${v.make} ${v.model}`}/><span className="vehicle-type">{v.type}</span></div><div className="vehicle-details"><div><h3>{v.make} <strong>{v.model}</strong></h3><p>{v.year} · {v.color} · {v.seats} seats</p></div><div className="price"><strong>{money(v.pricePerDay)}</strong><span>/ day</span></div></div><button className="book-button" onClick={()=>onBook(v)}>Reserve this ride <span>→</span></button></article>)}{!vehicles.length&&<div className="empty-state">No vehicles match those dates. Try widening your trip.</div>}</section></> }
function Trips({bookings,onExplore}) { return <section className="trips-view"><div className="section-heading"><div><p className="eyebrow">YOUR ROADWISE ACCOUNT</p><h2>My <em>trips.</em></h2></div></div>{bookings.length?<div className="trip-list">{bookings.map(b=><article className="trip-row" key={b.id}><img src={b.imageUrl} alt=""/><div><p className="eyebrow">{b.type} · {b.status}</p><h3>{b.vehicle}</h3><p>{date(b.startDate)} to {date(b.endDate)} · {b.pickupLocation}</p></div><strong>{money(b.totalCost)}</strong></article>)}</div>:<div className="empty-state">No trips yet. <button onClick={onExplore}>Explore the fleet →</button></div>}</section> }
function Payments({payments}) { return <section className="trips-view"><div className="section-heading"><div><p className="eyebrow">YOUR ROADWISE ACCOUNT</p><h2>Payment <em>history.</em></h2></div></div><div className="trip-list">{payments.map(p=><article className="trip-row" key={p.id}><div><p className="eyebrow">{p.status} · {p.method}</p><h3>{p.vehicle}</h3><p>{p.paidAt ? new Date(p.paidAt).toLocaleDateString() : "Awaiting payment"}</p></div><strong>{money(p.amount)}</strong></article>)}{!payments.length&&<div className="empty-state">No payments yet.</div>}</div></section> }
function Auth({onDone,onClose}) { const [mode,setMode]=useState("login"),[error,setError]=useState(""); const submit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{onDone(await api(`/api/auth/${mode === "login" ? "login" : "signup"}`,{method:"POST",body:JSON.stringify(Object.fromEntries(f))}));}catch(x){setError(x.message)}}; return <div className="modal-backdrop"><form className="booking-modal auth-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}>×</button><p className="eyebrow">{mode === "login" ? "WELCOME BACK" : "CREATE YOUR ACCOUNT"}</p><h2>{mode === "login" ? "Sign in" : "Start your journey"}</h2>{error&&<p className="form-error">{error}</p>}{mode==="signup"&&<label>Full name<input name="fullName" required/></label>}<label>Email<input name="email" type="email" required/></label>{mode==="signup"&&<label>Phone (optional)<input name="phone"/></label>}<label>Password<input name="password" type="password" minLength="8" required/></label><button className="search-button">{mode === "login" ? "Sign in" : "Create account"} <span>→</span></button><button type="button" className="switch-auth" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"New to Roadwise? Create an account":"Already have an account? Sign in"}</button><p className="demo-copy">Demo: alex@roadwise.local / customer123<br/>Admin: admin@roadwise.local / admin123</p></form></div> }
function Booking({vehicle,dates,onClose,onBook}) { return <div className="modal-backdrop"><form className="booking-modal" onSubmit={onBook}><button type="button" className="modal-close" onClick={onClose}>×</button><p className="eyebrow">RESERVE YOUR RIDE</p><h2>{vehicle.make} <em>{vehicle.model}</em></h2><p className="modal-sub">{money(vehicle.pricePerDay)} per day · {vehicle.type}</p><label>Pick-up and return location<input name="pickupLocation" required defaultValue="Downtown Station"/></label><div className="modal-dates"><label>Pick-up<input name="startDate" type="date" min={day()} defaultValue={dates.startDate}/></label><label>Return<input name="endDate" type="date" min={dates.startDate} defaultValue={dates.endDate}/></label></div><button className="search-button">Confirm reservation <span>→</span></button></form></div> }
function Admin({session,onLogout}) { const [tab,setTab]=useState("dashboard"),[data,setData]=useState({}),[notice,setNotice]=useState(""); const load=()=>Promise.all([api("/api/admin/summary",{},session.token),api("/api/admin/vehicles",{},session.token),api("/api/admin/bookings",{},session.token),api("/api/admin/maintenance",{},session.token)]).then(([summary,vehicles,bookings,maintenance])=>setData({summary,vehicles,bookings,maintenance})).catch(e=>setNotice(e.message)); useEffect(load,[]); const update=async(path,body)=>{try{await api(path,{method:"PATCH",body:JSON.stringify(body)},session.token);load()}catch(e){setNotice(e.message)}}; return <div className="app-shell admin-shell"><header className="topbar"><span className="brand"><span className="brand-mark">R</span>roadwise <small>ADMIN</small></span><button className="login-button" onClick={onLogout}>Log out</button></header>{notice&&<div className="notice">{notice}</div>}<nav className="admin-tabs">{["dashboard","vehicles","bookings","maintenance"].map(t=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>{tab==="dashboard"&&<section><div className="section-heading"><div><p className="eyebrow">OPERATIONS OVERVIEW</p><h2>Roadwise <em>dashboard.</em></h2></div></div><div className="admin-stats">{[["Ready vehicles",data.summary?.availableVehicles],["Active bookings",data.summary?.activeBookings],["Paid revenue",money(data.summary?.revenue)],["Maintenance items",data.summary?.maintenanceItems]].map(([a,b])=><div><p>{a}</p><strong>{b ?? "—"}</strong></div>)}</div></section>}{tab==="vehicles"&&<AdminTable title="Vehicle management" rows={data.vehicles} columns={["make","model","registrationNumber","type","pricePerDay","status"]} action={(r)=><select value={r.status} onChange={e=>update(`/api/admin/vehicles/${r.id}`,{status:e.target.value})}>{["available","maintenance","retired"].map(x=><option>{x}</option>)}</select>}/>} {tab==="bookings"&&<AdminTable title="Booking management" rows={data.bookings} columns={["customer","vehicle","startDate","endDate","totalCost","status"]} action={(r)=><select value={r.status} onChange={e=>update(`/api/admin/bookings/${r.id}`,{status:e.target.value})}>{["reserved","active","completed","cancelled"].map(x=><option>{x}</option>)}</select>}/>} {tab==="maintenance"&&<AdminTable title="Maintenance schedule" rows={data.maintenance} columns={["vehicle","serviceType","scheduledDate","status"]}/>}</div> }
function AdminTable({title,rows=[],columns,action}) { return <section><div className="section-heading"><h2>{title}</h2></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replace(/([A-Z])/g," $1")}</th>)}{action&&<th>update</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{columns.map(c=><td key={c}>{c.includes("Date")?date(r[c]):c==="pricePerDay"||c==="totalCost"?money(r[c]):r[c]}</td>)}{action&&<td>{action(r)}</td>}</tr>)}</tbody></table></div></section> }
createRoot(document.getElementById("root")).render(<App/>);
